#pragma warning disable CS8604 // Possible null reference argument.
#pragma warning disable CS8602 // Dereference of a possibly null reference.

#:package UiPath.Workflow@6.0.0-20240401-07
#:package UiPath.Activities.Api@24.10.1
#:package System.Activities.ViewModels@1.20260216.2
#:project D:\Development\Autossential-4\Autossential.Activities\Autossential.Activities.csproj

using System.Collections;
using System.Globalization;
using System.Resources;
using System.Text.RegularExpressions;

var rm = Autossential.Activities.Properties.Resources.ResourceManager;

using var sw = new StreamWriter("..\\Autossential.Activities\\Resources\\Resources.gen.cs");
sw.WriteLine($$"""
// Auto-Generated by dotnet script ResourceGenerator.csx at {{DateTime.Now:yyyyMMddHHmmss}}

using System;
using System.Globalization;

namespace Autossential.Activities.Properties;

internal static class ResourcesFn
{
    private static readonly IFormatProvider _culture = CultureInfo.InvariantCulture;

""");


var formattingMessages = rm.GetResourceSet(CultureInfo.InvariantCulture, true, true)
    .Cast<DictionaryEntry>()
    .Where(static p => p.Value.ToString().Contains("{0}"))
    .OrderBy(p => p.Key)
    .ToArray();



foreach (DictionaryEntry entry in formattingMessages)
{
    var count = Regex.Count(entry.Value.ToString(), @"\{\d+\}");
    var arguments = new string[count];
    var argsSign = new string[count];
    var paramNames = new string[count];
    sw.WriteLine($"""
        /// <summary>
        /// Looks up a localized string similar to '{entry.Value}'.
        /// </summary>"
    """);

    for (var i = 0; i < count; i++)
    {
        sw.WriteLine($@"    /// <param name=""arg{i}"">An object ({i}) to format.</param>");
        arguments[i] = "arg" + i;
        argsSign[i] = "object arg" + i;
    }

    sw.WriteLine($$"""
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string {{entry.Key}}Format({{string.Join(", ", argsSign)}})
        {
            return string.Format(_culture, Resources.{{entry.Key}}, {{string.Join(", ", arguments)}});
        }
    """);
}

sw.Write("}");
