// Auto-Generated by dotnet script ResourceGenerator.csx at 20250727153153

using System;
using System.Globalization;

namespace Autossential.Activities.Properties;

internal static class ResourcesFn
{
    private static readonly IFormatProvider _culture = CultureInfo.InvariantCulture;

    /// <summary>
    /// Looks up a localized string similar to 'An item with the same key has already been added. Key: {0}'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string AddToDictionary_ErrorMsg_KeyAlreadyExistsFormat(object arg0)
    {
        return string.Format(_culture, Resources.AddToDictionary_ErrorMsg_KeyAlreadyExists, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'The column index '{0}' does not exist on the DataTable.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string ExtractDataColumnValues_ErrorMsg_InvalidColumnIndexFormat(object arg0)
    {
        return string.Format(_culture, Resources.ExtractDataColumnValues_ErrorMsg_InvalidColumnIndex, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'The column '{0}' does not exist on the DataTable.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string ExtractDataColumnValues_ErrorMsg_InvalidColumnNameFormat(object arg0)
    {
        return string.Format(_culture, Resources.ExtractDataColumnValues_ErrorMsg_InvalidColumnName, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'The column {0} was not found in the specified table.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string FillDataTable_ErrorMsg_ColumnFormat(object arg0)
    {
        return string.Format(_culture, Resources.FillDataTable_ErrorMsg_Column, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'Please provide a value for {0} whose type is derived from {1}.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <param name="arg1">An object (1) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Validation_DerivedTypeErrorFormat(object arg0, object arg1)
    {
        return string.Format(_culture, Resources.Validation_DerivedTypeError, arg0, arg1);
    }
    /// <summary>
    /// Looks up a localized string similar to 'The value for {0} is null and couldn't be auto instantiated.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Validation_InstanceIsNullFormat(object arg0)
    {
        return string.Format(_culture, Resources.Validation_InstanceIsNull, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'Cannot be used outside of {0} activity.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Validation_ScopeErrorFormat(object arg0)
    {
        return string.Format(_culture, Resources.Validation_ScopeError, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'Cannot be used outside of {0} activities.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Validation_ScopesErrorFormat(object arg0)
    {
        return string.Format(_culture, Resources.Validation_ScopesError, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to 'Please provide a value of type {0} for {1}.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <param name="arg1">An object (1) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Validation_TypeErrorFormat(object arg0, object arg1)
    {
        return string.Format(_culture, Resources.Validation_TypeError, arg0, arg1);
    }
    /// <summary>
    /// Looks up a localized string similar to 'Please provide a value for {0}.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Validation_ValueErrorFormat(object arg0)
    {
        return string.Format(_culture, Resources.Validation_ValueError, arg0);
    }
}