// Auto-Generated by dotnet script ResourceGenerator.csx at 20260214133536

using System;
using System.Globalization;

namespace Autossential.Activities.Properties;

internal static class ResourcesFn
{
    private static readonly IFormatProvider _culture = CultureInfo.InvariantCulture;

    /// <summary>
    /// Looks up a localized string similar to 'Value for a required activity argument '{0}' was not supplied.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Common_ErrorMsg_ValueNotSuppliedFormat(object arg0)
    {
        return string.Format(_culture, Resources.Common_ErrorMsg_ValueNotSupplied, arg0);
    }
}