// Auto-Generated by dotnet script ResourceGenerator.csx at 20260405170211

using System.Globalization;

namespace Autossential.Activities.Properties;

internal static class ResourcesFn
{
    private static readonly IFormatProvider _culture = CultureInfo.InvariantCulture;

    /// <summary>
    /// Looks up a localized string similar to 'Value for a required activity argument '{0}' was not supplied.'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string Common_ErrorMsg_ValueNotSuppliedFormat(object arg0)
    {
        return string.Format(_culture, Resources.Common_ErrorMsg_ValueNotSupplied, arg0);
    }
    /// <summary>
    /// Looks up a localized string similar to '{0} {1} by {2}'.
    /// </summary>"
    /// <param name="arg0">An object (0) to format.</param>
    /// <param name="arg1">An object (1) to format.</param>
    /// <param name="arg2">An object (2) to format.</param>
    /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
    public static string IncrementDecrement_ViewModel_DynamicDisplayNameFormat(object arg0, object arg1, object arg2)
    {
        return string.Format(_culture, Resources.IncrementDecrement_ViewModel_DynamicDisplayName, arg0, arg1, arg2);
    }
}