//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autossential.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autossential.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Categories_Common {
            get {
                return ResourceManager.GetString("Categories_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Categories_Input {
            get {
                return ResourceManager.GetString("Categories_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Categories_Options {
            get {
                return ResourceManager.GetString("Categories_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Categories_Output {
            get {
                return ResourceManager.GetString("Categories_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies to continue executing the remaining activities even if the current activity failed. Only boolean values are allowed..
        /// </summary>
        internal static string Common_ContinueOnError_Description {
            get {
                return ResourceManager.GetString("Common_ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on error.
        /// </summary>
        internal static string Common_ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("Common_ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time in seconds for the file re-check. Any value less than 0.5 will be clamped to 0.5. Make sure to keep this value lesser than Timeout value..
        /// </summary>
        internal static string Common_IntervalSeconds_Description {
            get {
                return ResourceManager.GetString("Common_IntervalSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string Common_IntervalSeconds_DisplayName {
            get {
                return ResourceManager.GetString("Common_IntervalSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time in seconds to wait for the activity to run before an error is thrown. The default value is 30s..
        /// </summary>
        internal static string Common_TimeoutSeconds_Description {
            get {
                return ResourceManager.GetString("Common_TimeoutSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Common_TimeoutSeconds_DisplayName {
            get {
                return ResourceManager.GetString("Common_TimeoutSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waits until the file be available..
        /// </summary>
        internal static string WaitFile_Description {
            get {
                return ResourceManager.GetString("WaitFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path to be monitored..
        /// </summary>
        internal static string WaitFile_DirectoryPath_Description {
            get {
                return ResourceManager.GetString("WaitFile_DirectoryPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Path.
        /// </summary>
        internal static string WaitFile_DirectoryPath_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_DirectoryPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait File.
        /// </summary>
        internal static string WaitFile_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When true, the behavior of the activity changes to monitor a specific folder until find a file that corresponds to the search pattern informed..
        /// </summary>
        internal static string WaitFile_DynamicFile_Description {
            get {
                return ResourceManager.GetString("WaitFile_DynamicFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is dynamic.
        /// </summary>
        internal static string WaitFile_DynamicFile_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_DynamicFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file found..
        /// </summary>
        internal static string WaitFile_ErrorMsg_NoFileFound {
            get {
                return ResourceManager.GetString("WaitFile_ErrorMsg_NoFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file..
        /// </summary>
        internal static string WaitFile_FilePath_Description {
            get {
                return ResourceManager.GetString("WaitFile_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string WaitFile_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FileInfo object of the respective file when found..
        /// </summary>
        internal static string WaitFile_Result_Description {
            get {
                return ResourceManager.GetString("WaitFile_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string WaitFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search string to match against the names of files in path. This parameter can contain a combination of valid literal path and wildcard (* and ?) characters, but it doesn&apos;t support regular expressions. It supports a string or a collection of strings. Default value is all files (*.*)..
        /// </summary>
        internal static string WaitFile_SearchPattern_Description {
            get {
                return ResourceManager.GetString("WaitFile_SearchPattern_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Pattern.
        /// </summary>
        internal static string WaitFile_SearchPattern_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_SearchPattern_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        internal static string WaitFile_ViewModel_BrowseForFile {
            get {
                return ResourceManager.GetString("WaitFile_ViewModel_BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folder.
        /// </summary>
        internal static string WaitFile_ViewModel_BrowseForFolder {
            get {
                return ResourceManager.GetString("WaitFile_ViewModel_BrowseForFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waits until the file exists..
        /// </summary>
        internal static string WaitFile_WaitForExist_Description {
            get {
                return ResourceManager.GetString("WaitFile_WaitForExist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait For Exist.
        /// </summary>
        internal static string WaitFile_WaitForExist_DisplayName {
            get {
                return ResourceManager.GetString("WaitFile_WaitForExist_DisplayName", resourceCulture);
            }
        }
    }
}
