# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    
jobs:
  pack-push:
    env:
      project: ./source/Autossential.Activities.Design/Autossential.Activities.Design.csproj
      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Adding nuget package sources (MyGet-UiPath)
      run: dotnet nuget add source https://www.myget.org/F/uipath/ --name MyGet-UiPath
      
    - name: Adding nuget package sources (UiPath-Internal)
      run: dotnet nuget add source https://uipath.pkgs.visualstudio.com/Public.Feeds/_packaging/UiPath-Internal/nuget/v3/index.json --name UiPath-Internal
     
    - name: Restore
      run: dotnet restore ${{env.project}}
    
    - name: Pack
      run: dotnet pack ${{env.project}} -c Release -o Package
      
    - name: Push to NuGet
      run: |
        cd Package
        dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
